// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ed4qFdfWjACPreMHpop6u5yzeUedP9c',
    appId: '1:892301777512:web:a86f165ce7a1161da979dd',
    messagingSenderId: '892301777512',
    projectId: 'todoapp1-65100',
    authDomain: 'todoapp1-65100.firebaseapp.com',
    storageBucket: 'todoapp1-65100.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT6IWzsRCvr7R2Rmkf4JU5vXJYiElH_Ew',
    appId: '1:892301777512:android:3be59e72ab2616f2a979dd',
    messagingSenderId: '892301777512',
    projectId: 'todoapp1-65100',
    storageBucket: 'todoapp1-65100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3hPOspK_FdVasVUhiMKYqFg_fCsWYv2E',
    appId: '1:892301777512:ios:082ef0eee67363dba979dd',
    messagingSenderId: '892301777512',
    projectId: 'todoapp1-65100',
    storageBucket: 'todoapp1-65100.firebasestorage.app',
    iosBundleId: 'com.anas.todoapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3hPOspK_FdVasVUhiMKYqFg_fCsWYv2E',
    appId: '1:892301777512:ios:082ef0eee67363dba979dd',
    messagingSenderId: '892301777512',
    projectId: 'todoapp1-65100',
    storageBucket: 'todoapp1-65100.firebasestorage.app',
    iosBundleId: 'com.anas.todoapp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ed4qFdfWjACPreMHpop6u5yzeUedP9c',
    appId: '1:892301777512:web:45d0616fff798191a979dd',
    messagingSenderId: '892301777512',
    projectId: 'todoapp1-65100',
    authDomain: 'todoapp1-65100.firebaseapp.com',
    storageBucket: 'todoapp1-65100.firebasestorage.app',
  );

}